language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
env:
  - DJANGO=1.4.2
  - DJANGO=1.5
  - DJANGO=1.6
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q -e . --use-mirrors
script:
  - python setup.py test
